### PR TITLE
Use phi arguments instead of universe for local closures

### PR DESCRIPTION
**Pull request by abergeron**
This is complete and working in all cases of local closures that I could find.

It may have trouble in the future with `IfExp` if we add support for the `:=` operator.

### CODE REVIEW

**Comment by abergeron** [comment]
This PR will conflict with #406 for the parser tests.

**Comment by abergeron** [comment]
I'll fix the failing print tests once we merge #406 to avoid doing the work twice.

**Review by breuleux — APPROVED** [review]
Looks good to me

**Review by notoraptor — APPROVED** [review]
Looks good to me!

**Pull request merged**
